<?php
namespace Sagres\Framework\File;

/**
 * Test class for Action.
 * Generated by PHPUnit on 2012-03-06 at 12:25:35.
 */
class ActionTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Action
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Action;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Sagres\Framework\File\Action::getFileSet
     * @covers Sagres\Framework\File\Action::setFileSet
     */
    public function testSetGetFileSet()
    {
        $set = new Set();
        $this->object->setFileSet($set);
        $this->assertSame($set, $this->object->getFileSet());
    }

    private function resetFolder($folder) {
        $files = glob($folder . DIRECTORY_SEPARATOR . '*.*');

        foreach($files as $file) {
            unlink($file);
        }

        if(file_exists($folder)) {
            rmdir($folder);
        }
        mkdir($folder, 0777);
    }

    /**
     * @covers Sagres\Framework\File\Action::copyToFolder
     */
    public function testCopyToFolder()
    {
        $fileSet = new Set();
        $fileSet->addSet(__DIR__ . '/../../../../fixtures/folder1');

        $folder = __DIR__ . '/../../../../fixtures/copy';

        // make sure the folder is empty
        $this->resetFolder($folder);


        $this->object->setFileSet($fileSet);
        $this->object->copyToFolder($folder);

        $this->assertTrue(file_exists($folder . '/file1.txt'));
        $this->assertTrue(file_exists($folder . '/file2.yml'));
        $this->assertTrue(file_exists($folder . '/file3.txt'));
    }

    /**
     * @covers Sagres\Framework\File\Action::copyToFolder
     * @expectedException Sagres\Framework\File\Exception\notFound
     * @depends testCopyToFolder
     */
    public function testCopyToFolder_folderNotFound()
    {
        $fileSet = new Set();
        $fileSet->addSet(__DIR__ . '/../../../../fixtures/folder1');

        $folder = __DIR__ . '/../../../../fixtures/' . md5(time());

        $this->object->setFileSet($fileSet);
        $this->object->copyToFolder($folder);

    }
    /**
     * @covers Sagres\Framework\File\Action::copyToFolder
     * @expectedException Sagres\Framework\File\Exception\IOException
     * @depends testCopyToFolder
     */
    public function testCopyToFolder_BailoutIfOverwitingFiles()
    {
        $fileSet = new Set();
        $fileSet->addSet(__DIR__ . '/../../../../fixtures/folder1');

        $folder = __DIR__ . '/../../../../fixtures/' . md5(time());

        $this->object->setFileSet($fileSet);
        $this->object->copyToFolder($folder);

    }

    /**
     * @covers Sagres\Framework\File\Action::copyToFolder
     * @expectedException Sagres\Framework\File\Exception\InvalidPermissions
     * @depends testCopyToFolder
     */
    public function testCopyToFolder_foldernotWritable()
    {
        $fileSet = new Set();
        $fileSet->addSet(__DIR__ . '/../../../../fixtures/folder1');

        $folder = __DIR__ . '/../../../../fixtures/copy';

        chmod($folder, 0444);

        $this->object->setFileSet($fileSet);
        $this->object->copyToFolder($folder);

        //cleanup
        chmod($folder, 0777);
    }
}
?>
