<?php
namespace Sagres\Defenition;


/**
 * Test class for Execute.
 * Generated by PHPUnit on 2012-03-05 at 16:57:40.
 */
class ExecuteTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Execute
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Execute;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Sagres\Defenition\Execute::getType
     * @covers Sagres\Defenition\Execute::setType
     */
    public function testSetGetType()
    {
       $this->object->setType('foo');
       $this->assertEquals('foo', $this->object->getType());
    }

    /**
     * @covers Sagres\Defenition\Execute::getAction
     * @covers Sagres\Defenition\Execute::setAction
     * @todo Implement testGetAction().
     */
    public function testSetGetAction()
    {
        $this->object->setAction('foo');
        $this->assertEquals('foo', $this->object->getAction());
    }
}
?>
